name: Mise à jour automatique du catalogue

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Ajoute ce bouton pour tester manuellement !

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: 🟢 Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # On force Node 24 pour 2026

      - name: ⚙️ Exécution du script
        # On ajoute "|| exit 1" pour être sûr de voir l'erreur si le script échoue
        run: node get_templates.js

      - name: 📤 Sauvegarde
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "🚀 Mise à jour auto [skip ci]" || echo "Aucune modification à commit"
          git push
